extends Node

enum Elements {
	NONE,
	BATTERY,
	DISPLAY,
	INVERTER,
	LAMP,
	POWER_INVERTER,
	POWER_RELAY,
	RELAY,
	SWITCH,
	WIRE,
	AND,
	OR,
	NOT_AND,
	NOT_OR,
	EX_AND,
	EX_OR,
	HALF_ADDER,
	FULL_ADDER,
	BUTTON,
	SELECTOR,
	TRIGGER_RESET,
	TRIGGER_LEVEL,
	TRIGGER_LEVEL_RESET,
	TRIGGER_FRONT
}

enum Connectors {
	NONE, IN, OUT
}

enum Levels {
	NONE, TUTORIAL, CAMPAIGN, SANDBOX, SETTINGS
}

const COLORS: Dictionary = {
	ENERGY_ON = Color("#FDDF19"),
	ENERGY_OFF = Color("#1991E8"),
	OUTLINE = Color("#EEEEEE"),
	TOOGLE_BUTTON = Color("#333333"),
	DEFAULT_BUTTON = Color("#555555"),
	SAFE_AREA_ALARM = Color("#CE2E59")
}

const FONTS: Dictionary = {
	DEFAULT_FONT_SIZE = 24,
	COLOR_LABEL_FONT_SIZE = 28,
	TITLE_FONT_SIZE = 64,
}

const GAME: Dictionary = {
	CURSOR_TYPE = -1,
	MAXIMUM_ELEMENTS_TO_SELECT = 2048,
	FREQUENCY = 4,
	BUTTON_DELAY = 16,
	MINIMAL_WIRE_LENGTH = 8,
	CONNECTED_WIRE_LENGTH = 512,
	REPULSE_WIRE_LENGTH = 48,
	WIRE_ALPHA = 0.6,
	DEFAULT_FILE_NAME = "untitled",
	FILE_EXTENSION = "machine",
	SAVE_GAME_DIR = "user://",
	LAST_FILE = ".last_file"
}

const CAMERA: Dictionary = {
	ZOOM_MIN = 0.4,
	ZOOM_MAX = 1.0,
	PAN_SPEED = 8.0,
	DRAG_SPEED = 1.5
}
